[package]
name = "radicle-surf"
description = "A code surfing library for VCS file systems"
readme = "README.md"
version = "0.2.1"
authors = ["Monadic GmbH <radicle@monadic.xyz>"]
edition = "2018"
homepage = "https://github.com/radicle-dev/radicle-surf"
repository = "https://github.com/radicle-dev/radicle-surf"
license = "GPL-3.0-only"

[dependencies]
git2 = "0.12"
nonempty = "0.2"
thiserror = "1.0"

[dev-dependencies]
pretty_assertions = "0.6"
proptest = "0.9"
